### ISSUE TITLE
CSS Fix

### ISSUE THREAD

**Issue by jfeliciani** [Jake13f/Forum#1]
The Thread list titles overlap when moving to smaller resolutions and display under each other.
<img width="878" alt="screen shot 2017-01-19 at 12 31 40 am" src="https://cloud.githubusercontent.com/assets/14061733/22094826/527ebe6c-ddde-11e6-8387-5bead9409f66.png">

**Comment by JeffProgrammer** [comment]
Need custom code potentially to handle mobile browsers / small resolutions.

**Comment by JeffProgrammer** [comment]
We could use bootstrap @Jake13f :) :) :) :)
